"""Atualização do db

Revision ID: e90ecbd84b9a
Revises: 895d3e8835bc
Create Date: 2025-01-25 00:14:45.680030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90ecbd84b9a'
down_revision = '895d3e8835bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ano', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cambio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('combustivel', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('final_da_placa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('cor')
        batch_op.drop_column('final_da_placa')
        batch_op.drop_column('combustivel')
        batch_op.drop_column('cambio')
        batch_op.drop_column('km')
        batch_op.drop_column('Ano')

    # ### end Alembic commands ###
